language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
  include:
    - php: 7.1
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit